### PR TITLE
Jeg får " 401 (Unauthorized)" i console #117

### PR DESCRIPTION
**Pull request by olavea**
Here is one doc:
https://github.com/encrypted-dev/userbase-samples/blob/master/ugliest-todo/payments.html#L87-L93

Here in vanilla javascript it works:
https://github.com/olavea/The-Unicorny-TimeShip-App/blob/the-unicorny-timeship-app-%23117/1_Userbase_Stripe/code%20ugly-todo.html

### CODE REVIEW

**Comment by olavea** [comment]
@raae 

userbase.purchaseSubscription works in TimeShip.html
POW-BRANCH_stripe _#117_ userbase purchaseSubscription_works_in_timeship_45-267

userbase purchaseSubscription is not a function in POW! 
POW-BRANCH_stripe _#117_ userbase purchaseSubscription is not a function_44-266

**Comment by raae** [comment]
It seems `yarn upgrade` does not work as I though. run `yarn add userbase-js` instead and package.json will update.

You should not need to do anything with sign in. All your work should be in PaymentForm, instead of using stripe directly you use the new `purchaseSubscription`.

However it looks like it only supports one plan? We need the option to choose between two plans: yearly and monthly. We can ask for that, and maybe help Userbase make it.

**Comment by olavea** [comment]
- [ ] All my work is in PaymentForm,
- [ ] I did Yarn add userbase-js
- [ ] Should I make some errorHandling?

POW-BRANCH_stripe _#117_ userbase purchaseSubscription_WORKS_49-271

**Comment by raae** [comment]
Do not continue on this branch. It's to old.

**Pull request closed without merging**
