### PR TITLE
Add a LEGO Joker image to the 404.js page #272

### PR DESCRIPTION
**Pull request by olavea**

### CODE REVIEW

**Comment by olavea** [comment]
[1](https://images.unsplash.com/photo-1525097522700-a4b80b773931?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGxlZ28lMjBiYXRtYW58ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60)
 
[2](https://images.unsplash.com/photo-1584847642060-a46e239155a8?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NjV8fGxlZ28lMjBoZXJvfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60)
  
[3](https://images.unsplash.com/photo-1611250535839-94b88cf88bba?ixid=MnwxMjA3fDB8MHxzZWFyY2h8ODd8fGxlZ28lMjBoZXJvfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60)
  
[4](https://images.unsplash.com/photo-1518331334341-85b0b2f4781a?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTIwfHxsZWdvJTIwaGVyb3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60)
  
[5](url)
  
[6](https://images.unsplash.com/photo-1542410613-d073472c3135?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTMzfHxsZWdvJTIwaGVyb3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60)
  
[7](https://unsplash.com/photos/XzEqlPQsLdI)
  
[8](https://images.unsplash.com/photo-1532169627909-dc6319871078?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8bGVnbyUyMGJhdG1hbnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60)
  
[9](https://images.unsplash.com/photo-1538448174498-9956c159edb0?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTQ2fHxsZWdvJTIwYmF0bWFufGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60)
  
[10](https://images.unsplash.com/photo-1518331647614-7a1f04cd34cf?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTMxfHxsZWdvJTIwYmF0bWFufGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60)
  
[11](https://images.unsplash.com/photo-1472457847783-3d10540b03d7?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzZ8fGxlZ28lMjBoZXJvfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60)
 
[12](https://images.unsplash.com/photo-1610398207451-7bf50e622c16?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjQ2fHxsZWdvJTIwYmF0bWFufGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60)

 
[13](https://images.unsplash.com/photo-1613834927301-1c96a302e074?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjk5fHxsZWdvJTIwYmF0bWFufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60)

 
[14](https://images.unsplash.com/photo-1559715541-5daf8a0296d0?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzExfHxsZWdvJTIwYmF0bWFufGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60)

 
[15](https://images.unsplash.com/photo-1554579653-17cdf3bfbca6?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzkxfHxsZWdvJTIwYmF0bWFufGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60)

**Comment by raae** [comment]
I commented in #269, add both copy and the photo in that branch.

**Review by raae — CHANGES_REQUESTED** [review]
I commented in #269, add both copy and the photo in that branch.

**Comment by raae** [comment]
Will be solved by #269

**Pull request closed without merging**
